package fr.forumhfr.redface2.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val Seed = Color(0xFFA62C2C)

val RedfaceLightColorScheme = lightColorScheme(
    primary = Color(0xFF8E1D24),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD9),
    onPrimaryContainer = Color(0xFF3B070B),
    secondary = Color(0xFF775655),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD9),
    onSecondaryContainer = Color(0xFF2C1515),
    tertiary = Color(0xFF735B2E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEA5),
    onTertiaryContainer = Color(0xFF261900),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F7),
    onBackground = Color(0xFF231919),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF231919),
    surfaceVariant = Color(0xFFF4DDDC),
    onSurfaceVariant = Color(0xFF534342),
    outline = Color(0xFF857371),
    outlineVariant = Color(0xFFD7C1BF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF392E2D),
    inverseOnSurface = Color(0xFFFFEDEB),
    inversePrimary = Color(0xFFFFB3B1),
    surfaceDim = Color(0xFFE8D6D5),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1F0),
    surfaceContainer = Color(0xFFFCEBEA),
    surfaceContainerHigh = Color(0xFFF6E5E4),
    surfaceContainerHighest = Color(0xFFF1DFDE),
    surfaceTint = Seed,
)

val RedfaceDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB3B1),
    onPrimary = Color(0xFF561D20),
    primaryContainer = Color(0xFF733338),
    onPrimaryContainer = Color(0xFFFFDAD9),
    secondary = Color(0xFFE6BDBC),
    onSecondary = Color(0xFF442928),
    secondaryContainer = Color(0xFF5C3F3E),
    onSecondaryContainer = Color(0xFFFFDAD9),
    tertiary = Color(0xFFE2C28C),
    onTertiary = Color(0xFF402D04),
    tertiaryContainer = Color(0xFF594319),
    onTertiaryContainer = Color(0xFFFFDEA5),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1111),
    onBackground = Color(0xFFF0DEDC),
    surface = Color(0xFF1A1111),
    onSurface = Color(0xFFF0DEDC),
    surfaceVariant = Color(0xFF534342),
    onSurfaceVariant = Color(0xFFD7C1BF),
    outline = Color(0xFF9F8C8A),
    outlineVariant = Color(0xFF534342),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF0DEDC),
    inverseOnSurface = Color(0xFF392E2D),
    inversePrimary = Color(0xFF8E1D24),
    surfaceDim = Color(0xFF140E0E),
    surfaceBright = Color(0xFF423635),
    surfaceContainerLowest = Color(0xFF120B0B),
    surfaceContainerLow = Color(0xFF221919),
    surfaceContainer = Color(0xFF271D1D),
    surfaceContainerHigh = Color(0xFF322727),
    surfaceContainerHighest = Color(0xFF3D3131),
    surfaceTint = Color(0xFFFFB3B1),
)

val RedfaceAmoledColorScheme = darkColorScheme(
    primary = Color(0xFFFFB3B1),
    onPrimary = Color(0xFF561D20),
    primaryContainer = Color(0xFF733338),
    onPrimaryContainer = Color(0xFFFFDAD9),
    secondary = Color(0xFFE6BDBC),
    onSecondary = Color(0xFF442928),
    secondaryContainer = Color(0xFF5C3F3E),
    onSecondaryContainer = Color(0xFFFFDAD9),
    tertiary = Color(0xFFE2C28C),
    onTertiary = Color(0xFF402D04),
    tertiaryContainer = Color(0xFF594319),
    onTertiaryContainer = Color(0xFFFFDEA5),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF000000),
    onBackground = Color(0xFFF0DEDC),
    surface = Color(0xFF000000),
    onSurface = Color(0xFFF0DEDC),
    surfaceVariant = Color(0xFF4A3A3A),
    onSurfaceVariant = Color(0xFFD7C1BF),
    outline = Color(0xFF9F8C8A),
    outlineVariant = Color(0xFF4A3A3A),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF0DEDC),
    inverseOnSurface = Color(0xFF221919),
    inversePrimary = Color(0xFF8E1D24),
    surfaceDim = Color(0xFF000000),
    surfaceBright = Color(0xFF2B2020),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceContainerLow = Color(0xFF050303),
    surfaceContainer = Color(0xFF0B0909),
    surfaceContainerHigh = Color(0xFF130F0F),
    surfaceContainerHighest = Color(0xFF1B1616),
    surfaceTint = Color(0xFFFFB3B1),
)

// --- « Rouge REDFACE1 » accent (TU 2788511) -----------------------------------------------------
// Vivid red scheme seeded from #F44336 (Redface 1's `theme_primary`). Deliberately higher-chroma
// than the default maroon/rose scheme above so the switch reads clearly: light `primary` jumps from
// the muted #8E1D24 to the punchy #C62828, and dark `primary` goes coral-red (#FF8A80) instead of the
// pale pink #FFB3B1. The neutral surfaces stay the same warm greys as the default scheme on purpose —
// only the primary/secondary roles change, so the window background never differs between accents.

private val RedSeed = Color(0xFFF44336)

val RedfaceRedLightColorScheme = lightColorScheme(
    primary = Color(0xFFC62828),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD5),
    onPrimaryContainer = Color(0xFF410001),
    secondary = Color(0xFF8C4A43),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBD2),
    onSecondaryContainer = Color(0xFF3A0905),
    tertiary = Color(0xFF735B2E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEA5),
    onTertiaryContainer = Color(0xFF261900),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F6),
    onBackground = Color(0xFF231918),
    surface = Color(0xFFFFF8F6),
    onSurface = Color(0xFF231918),
    surfaceVariant = Color(0xFFF5DDD9),
    onSurfaceVariant = Color(0xFF53433F),
    outline = Color(0xFF85736F),
    outlineVariant = Color(0xFFD8C2BD),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF392E2C),
    inverseOnSurface = Color(0xFFFFEDE9),
    inversePrimary = Color(0xFFFFB3AC),
    surfaceDim = Color(0xFFE8D6D2),
    surfaceBright = Color(0xFFFFF8F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1ED),
    surfaceContainer = Color(0xFFFCEAE6),
    surfaceContainerHigh = Color(0xFFF7E4E0),
    surfaceContainerHighest = Color(0xFFF1DFDA),
    surfaceTint = RedSeed,
)

val RedfaceRedDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFF8A80),
    onPrimary = Color(0xFF690007),
    primaryContainer = Color(0xFFB71C1C),
    onPrimaryContainer = Color(0xFFFFDAD5),
    secondary = Color(0xFFE7BDB6),
    onSecondary = Color(0xFF442925),
    secondaryContainer = Color(0xFF5D3F3A),
    onSecondaryContainer = Color(0xFFFFDBD2),
    tertiary = Color(0xFFE2C28C),
    onTertiary = Color(0xFF402D04),
    tertiaryContainer = Color(0xFF594319),
    onTertiaryContainer = Color(0xFFFFDEA5),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1110),
    onBackground = Color(0xFFF0DEDA),
    surface = Color(0xFF1A1110),
    onSurface = Color(0xFFF0DEDA),
    surfaceVariant = Color(0xFF53433F),
    onSurfaceVariant = Color(0xFFD8C2BD),
    outline = Color(0xFFA08C87),
    outlineVariant = Color(0xFF53433F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF0DEDA),
    inverseOnSurface = Color(0xFF392E2C),
    inversePrimary = Color(0xFFC62828),
    surfaceDim = Color(0xFF140D0C),
    surfaceBright = Color(0xFF423735),
    surfaceContainerLowest = Color(0xFF120B0A),
    surfaceContainerLow = Color(0xFF221917),
    surfaceContainer = Color(0xFF261D1B),
    surfaceContainerHigh = Color(0xFF312726),
    surfaceContainerHighest = Color(0xFF3D3130),
    surfaceTint = Color(0xFFFF8A80),
)
